// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HAttendanceOperation
{
    public int Id { get; set; }

    public DateTime EnterDate { get; set; }

    public DateTime ExitDate { get; set; }

    public short StaffId { get; set; }

    public byte? WorkedHours { get; set; }

    public virtual HStaff Staff { get; set; }
}