// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HDCountry
{
    public byte Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<HGuestBooking> HGuestBookings { get; set; } = new List<HGuestBooking>();

    public virtual ICollection<HGuestLiving> HGuestLivings { get; set; } = new List<HGuestLiving>();

    public virtual ICollection<HHotel> HHotels { get; set; } = new List<HHotel>();
}