// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HFeedback
{
    public int Id { get; set; }

    public string Text { get; set; }

    public DateTime? Date { get; set; }

    public byte StatusId { get; set; }

    public byte Rate { get; set; }

    public byte? UserId { get; set; }

    public virtual ICollection<HFeedbackAnswer> HFeedbackAnswers { get; set; } = new List<HFeedbackAnswer>();

    public virtual HDFeedbackStatus Status { get; set; }

    public virtual HUser User { get; set; }
}