// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HFeedbackAnswer
{
    public int Id { get; set; }

    public string Text { get; set; }

    public DateTime? Date { get; set; }

    public int FeedbackId { get; set; }

    public byte UserId { get; set; }

    public virtual HFeedback Feedback { get; set; }

    public virtual HUser User { get; set; }
}