// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HGuestBooking
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PassportNumber { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public byte CountryId { get; set; }

    public string City { get; set; }

    public virtual HDCountry Country { get; set; }

    public virtual ICollection<HBooking> HBookings { get; set; } = new List<HBooking>();
}