// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HLiving
{
    public int Id { get; set; }

    public int Number { get; set; }

    public DateTime CheckInDate { get; set; }

    public DateTime CheckOutDate { get; set; }

    public decimal Amount { get; set; }

    public string Comments { get; set; }

    public short RoomId { get; set; }

    public byte StatusId { get; set; }

    public int? BookingId { get; set; }

    public int GuestId { get; set; }

    public virtual HBooking Booking { get; set; }

    public virtual HGuestLiving Guest { get; set; }

    public virtual HRoom Room { get; set; }

    public virtual HDLivingStatus Status { get; set; }
}