// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HotelApp2.Models;

public partial class Hotel_DBContext : DbContext
{
    public Hotel_DBContext(DbContextOptions<Hotel_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HDRoomType> HDRoomTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HDRoomType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__H_RoomTy__3214EC07BED2BCC0");

            entity.ToTable("H_d_RoomType");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Name)
                .HasMaxLength(18)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("numeric(6, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}