// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HPayment
{
    public int Id { get; set; }

    public byte MethodId { get; set; }

    public byte StatusId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Amount { get; set; }

    public int BookingId { get; set; }

    public virtual HBooking Booking { get; set; }

    public virtual HDPaymentMethod Method { get; set; }

    public virtual HDPaymentStatus Status { get; set; }
}