// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HRoom
{
    public short Id { get; set; }

    public string Number { get; set; }

    public byte AvailabilityStatusId { get; set; }

    public byte CleaningStatusId { get; set; }

    public byte TypeId { get; set; }

    public byte HotelId { get; set; }

    public byte Etaj { get; set; }

    public byte NrRooms { get; set; }

    public virtual HDAvailabilityStatus AvailabilityStatus { get; set; }

    public virtual HDCleaningStatus CleaningStatus { get; set; }

    public virtual HHotel Hotel { get; set; }

    public virtual HDRoomType Type { get; set; }
}