// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HSalary
{
    public int Id { get; set; }

    public decimal? Amount { get; set; }

    public short StaffId { get; set; }

    public byte StatusId { get; set; }

    public DateTime DateModified { get; set; }

    public virtual HStaff Staff { get; set; }

    public virtual HDSalaryStatus Status { get; set; }
}