// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HStaff
{
    public short Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string Idnp { get; set; }

    public string PassportNumber { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public byte FunctionId { get; set; }

    public DateTime HireDate { get; set; }

    public byte HotelId { get; set; }

    public short NrContract { get; set; }

    public byte CountryId { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public virtual HDCountry Country { get; set; }

    public virtual HStaffFunction Function { get; set; }

    public virtual ICollection<HAttendanceOperation> HAttendanceOperations { get; set; } = new List<HAttendanceOperation>();

    public virtual ICollection<HSalary> HSalaries { get; set; } = new List<HSalary>();

    public virtual HHotel Hotel { get; set; }
}