// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HUser
{
    public byte Id { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public short StaffId { get; set; }

    public virtual ICollection<HCleaning> HCleanings { get; set; } = new List<HCleaning>();

    public virtual ICollection<HFeedbackAnswer> HFeedbackAnswers { get; set; } = new List<HFeedbackAnswer>();

    public virtual ICollection<HFeedback> HFeedbacks { get; set; } = new List<HFeedback>();

    public virtual ICollection<HUsersAction> HUsersActions { get; set; } = new List<HUsersAction>();

    public virtual HStaff Staff { get; set; }

    public virtual ICollection<HDUserRole> IdRoles { get; set; } = new List<HDUserRole>();
}