// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelApp2.Models;

public partial class HUsersAction
{
    public short Id { get; set; }

    public string Name { get; set; }

    public DateTime? Date { get; set; }

    public byte UserId { get; set; }

    public virtual HUser User { get; set; }
}